name: CI
on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build - Windows
      - name: Build project for Windows
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.14f1
          targetPlatform: StandaloneWindows64

      # Build - OSX
      - name: Build project for OSX
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.14f1
          targetPlatform: StandaloneOSX

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build